//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayerEF2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public string DepartureStation { get; set; }
        public string ArrivalStation { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string Transport { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public string Number { get; set; }
    
        public virtual IATAC IATAC { get; set; }
        public virtual IATAC IATAC1 { get; set; }
    }
}
